#ifndef COPA_PROTOTIPOS_CONFIGURACAO_MQH
#define COPA_PROTOTIPOS_CONFIGURACAO_MQH

bool ValidarAmbienteConta();
void InicializarEstados();
bool InicializarIndicadores();
void LiberarIndicadores();
void SincronizarMagicParametros(bool forcar=false);
long MagicCompraAtual();
long MagicVendaAtual();
long MagicPainelAAtual();
long MagicPainelBAtual();
bool ValidarMagicsConfiguradosFIX252(string &motivo);
string MarcadorComentarioOperacionalFIX252(string comentarioBase);
string IDInstanciaAtual();
string Base36FIX304(long valor,int largura);
long HashTextoFIX304(string texto);
void InicializarIdentidadeUnicaFIX304();
void AtualizarHeartbeatIdentidadeFIX304();
void EncerrarHeartbeatIdentidadeFIX304();
string ExtrairGeracaoComentarioFIX304(string comentario);
string ExtrairCicloComentarioFIX304(string comentario);
bool ComentarioTemIdentidadeAtualFIX304(string comentario,long magic);
string CicloAtualMagicFIX304(long magic,bool criarSeNecessario);
void EncerrarCicloIdentidadeLocalFIX304();
string ComentarioComIdentidadeMagicFIX304(string comentarioBase,long magic);
int ContarPosicoesMagicFIX304(long magic,double &contratos);
bool DealEhDoRoboHistorico(ulong deal);
void AtualizarHistoricoLongoEmRodizio(datetime agora, datetime inicioHoje, datetime inicioOntem, datetime inicio7, datetime inicio15, datetime inicio30, datetime inicioTudo, datetime corteSessao);
void AtualizarHistoricoSelecionadoAgora();
void CarregarTodasMatrizes();
void CarregarMatrizJanelas();
void CarregarMatrizAumentos();
void CarregarMatrizSaida();
string MontarLinhaJanelaClara(string configuracao, string filtros);
string FaixaHorarioCompacta(string lista, int indice);
bool HorarioCompactoPermitidoAgora(string lista);
void InvalidarSnapshotTotalABFIX292();
void ValidarJanelasClaras();
bool MinutoDentroJanelaValor(int minuto, RegraJanela &j);
RegraJanela ParseJanela(string linha);
RegraAumento ParseAumento(string linha);
void ParseTrailAumentoFIX282(string campo, double &ativar, double &passo);
void ParseGerenciadorAumentos(string linha);
void ParseScoreAumentos(string linha);
bool ModoAumentoSomenteScore();
double MinimoScoreAumentoNivel(int indiceZero);
double QualidadeVolumeScoreAdaptativo(bool quantidade, bool &aprovado, string &detalhe);
double CalcularScoreAumentoDedicado(ENUM_LADO_ROBO lado, string &detalhe);
bool ScoreAumentoAutoriza(EstadoLado &estado, int indiceZero, string &detalhe);
string TextoScoreAumentoNivel(EstadoLado &estado, int indiceZero);
double MinimoScoreVolumeAumentoFIX334(int indiceZero);
void AtualizarScoreVolumeCandleFIX335();
double CalcularScoreVolumeAumentoFIX334(ENUM_LADO_ROBO lado, string &detalhe);
bool ScoreVolumeAumentoAutorizaFIX334(ENUM_LADO_ROBO lado, int indiceZero, string &detalhe);
string TextoScoreVolumeAumentoFIX334(ENUM_LADO_ROBO lado, int indiceZero);
void AtualizarHiLo8ESTR();
void AtualizarVisualHilo14STR4FIX418(bool forcar=false);
void LimparVisualHilo14STR4FIX418();
void AtualizarDXAdaptativoFIX411(bool forcar=false);
bool DXAdaptativoAutorizaFIX411(ENUM_LADO_ROBO lado,bool aumento,int nivelAumento,string &detalhe);
void ConsumirSinalDXAposOrdemFIX417(ENUM_LADO_ROBO lado,bool aumento,int nivelAumento);
void AtualizarPlotagemDXAdaptativoFIX411();
void LimparPlotagemDXAdaptativoFIX411();
string RegimeDXFIX411(double forcaMax);

double CalcularAgressaoCompradoraTicks(int quantidadeTicks);
double AgressaoDirecionalPercentual(ENUM_LADO_ROBO lado);
double CalcularAgressaoCompradoraCandleFIX258(datetime inicio, datetime fim);
double VolumeQuantidadeBarraContraFIX261(int shift);
double VolumeFinanceiroBarraContraFIX261(int shift);
bool VolumeQtdFinHistoricoContraFIX261(int shift, double &ratioQtd, double &ratioFin);
double RSICalculadoManualContraFIX262(int shift, int periodo=14);
double RSIHistoricoContraFIX261(int shift);
bool HiLoSTRHistoricoContraFIX261(int shift, bool &hiloCompra, bool &hiloVenda, bool &strCompra, bool &strVenda);
double AgressaoCompradoraEstimadaContraFIX261(int shift);
double MediaFechamentoAnteriorContraFIX265(int shift, int periodo);
double ATRManualContraFIX265(int shift, int periodo);
bool CandleReversaoBasicoContraFIX265(int shift, ENUM_LADO_ROBO ladoContra);
double MediaFechamentoIncluindoAtualContraFIX266(int shift, int periodo);
bool RetornoRSIConfirmadoContraFIX266(int shift, ENUM_LADO_ROBO ladoContra, double rsiAtual);
bool QuebraEstruturaContraFIX266(int shift, ENUM_LADO_ROBO ladoContra);
bool CruzamentoMedia8ContraFIX266(int shift, ENUM_LADO_ROBO ladoContra);
bool CalcularFiboExaustaoContraFIX269(int shiftSetup, ENUM_LADO_ROBO ladoContra, double &nivelFibo, double &extensaoATR, double &extensaoEstrutural);
bool ConfirmacaoSegundoCandleContraFIX267(int shift, ENUM_LADO_ROBO ladoContra, int shiftGatilho, double extremaSetup, double nivelFiboSetup);
bool ExisteSinalRecenteContraFIX265(int shift, ENUM_LADO_ROBO ladoContra);
bool PrepararCacheOTTFIX271(int maxShift);
double ValorSuporteOTTFIX271(int shift);
double ValorLinhaOTTFIX271(int shift);
void PlotarLinhasOTTFIX271();
void LimparLinhasOTTFIX271();
bool AvaliarCandleContraOTTFIX271(int shift, ENUM_LADO_ROBO &ladoContra, double &rsi, double &agrCompra, double &ratioQtd, double &ratioFin, int &confirmacoes);
bool AvaliarCandleContraCruzamentoFIX270(int shift, ENUM_LADO_ROBO &ladoContra, double &rsi, double &agrCompra, double &ratioQtd, double &ratioFin, int &confirmacoes);
bool AvaliarCandleContraCirurgicoFIX265(int shift, ENUM_LADO_ROBO &ladoContra, double &rsi, double &agrCompra, double &ratioQtd, double &ratioFin, int &confirmacoes);
bool AvaliarCandleContraFIX261(int shift, bool usarAgressaoAtual, ENUM_LADO_ROBO &ladoContra, double &rsi, double &agrCompra, double &ratioQtd, double &ratioFin, int &confirmacoes);
int ContarObjetosCandlesContraFIX262();
void AtualizarDiagnosticoCandlesContraFIX263();
void CarregarHistoricoCandlesContraFIX261();
void PlotarCandleContraFIX258(datetime tempoBarra, ENUM_LADO_ROBO entradaContra, double precoAbertura, double maxima, double minima, double fechamento);
void LimitarCandlesContraFIX258();
void LimparCandlesContraFIX258();
void AtualizarCandlesContraFIX258(bool forcar=false);
string CombinarLinhaFiltro(string linhaBase, string linhaFiltros);
string NormalizarFiltrosHumanizados(string linha);
void AplicarConfirmacaoLinhasAumentos();
bool ExtrairPrimeiroNumeroAPartir(string texto, int inicio, double &valor, int &fimNumero);
double NumeroDepoisDoMarcador(string texto, string marcador, double padrao);
bool DoisNumerosDepoisDoMarcador(string texto, string marcador, double &primeiro, double &segundo);
int CandlesNoFormatoCurto(string texto, int padrao);
void AplicarParametrosCompactos();
void AplicarAumentoCompactoNosInputs(int nivel, string linha);
void ParseRiscoOperacao(string linha);
void ParseRiscoDiario(string linha);
void ParseProtecaoLucro(string linha);
void ParseOperacaoLonga(string linha);
void AplicarParametrosHumanizados();
void AplicarAumentoHumanizado(int idx, bool ativo, double qtd, int tempoMinutos, double gatilhoReais, int distanciaPontos, double protecaoPercent, string filtrosLinha);
void AplicarFiltrosHumanizadosAoAumento(int idx);


#endif // COPA_PROTOTIPOS_CONFIGURACAO_MQH
