#ifndef COPA_PROTOTIPOS_MOTOR_MQH
#define COPA_PROTOTIPOS_MOTOR_MQH

void AplicarFiltroToken(RegraFiltros &f, string token);
string Trim(string s);
string Upper(string s);
bool IsOn(string s);
double ExtrairNumero(string s);
int ExtrairInteiro(string s);
string GetCampo(string linha, string chave, string padrao="");
string NormalizarLinhaAumentoHumanizada(string linha);
string GetArg(string args, string chave, string padrao="");
int HorarioParaMinutos(string hhmm);
bool ParseHorario(string horario, int &ini, int &fim);
ENUM_LADO_ROBO ParseLado(string s);
string NomeLado(ENUM_LADO_ROBO lado);
void AtualizarNovoCandle();
void AtualizarMercado();
void AtualizarEstadosDePosicao();
void AtualizarEstadosPainelFinanceiro();
void PrepararSlotPainel(EstadoLado &slot, string nome, long magic, ENUM_LADO_ROBO slotHistorico);
void AtualizarEstadoLado(EstadoLado &estado);
void ResetarDadosCicloSemPosicao(EstadoLado &estado);
void SincronizarResultadoFechadoDiaComHistorico();
double LucroAbertoPosicaoSelecionada(long tipo);
double LucroAbertoPosicaoSelecionadaFIX354(long tipo);
void AtualizarCamposFinanceirosCriticosFIX354(bool forcarRedraw=false);
double GainHeadEfetivoFIX362();
double LossHeadEfetivoFIX362();
string AssinaturaParametrosUsuarioFIX362();
bool SincronizarParametrosUsuarioFIX362(bool forcar=false, string origem="AUTO");
void MontarFotoFinanceiraPainelFIX362(FotoFinanceiraPainelFIX362 &foto, bool forcar=false);
void AtualizarGanhoQtdReaisFIX362(bool forcar=false);
string TextoGanhoQtdReaisFIX362(ENUM_LADO_ROBO lado, bool head=false);
bool AtualizarObjetoValorFIX354(string nome,string texto,color cor,int &ok,int &total);
void RegistrarAuditoriaCamposPainelFIX354(int objOk,int objTotal,int formulaOk,int formulaTotal,string movimento,double bid,double ask,double abertoC,double abertoV,double realizadoC,double realizadoV,double saldoC,double saldoV);
ENUM_LADO_ROBO LadoDaPosicaoAtual(EstadoLado &estado);
void AtualizarRiscoMestre();
void AtualizarHistoricoObrigatorio();
int IntervaloHistoricoEfetivo();
int IntervaloPainelEfetivo();
void ArmarAtualizacaoHistoricoRapidaFIX227(string motivo);
void ProcessarAtualizacaoHistoricoRapidaFIX227();
void ForcarAtualizacaoHistoricoPainel(string motivo);
void AtualizarVisualHistoricoRapido();
void RedesenharAbasHistoricoRapidas(string pfx, int tx, int ty, int fonte);
bool PainelCliqueHistorico(string objeto);
bool PainelCliqueModoVisual(string objeto);
void DesenharBotoesModoPainel(string pfx, int x, int y, int fonte);
void PnlBotaoModo(string nome, string texto, int x, int y, int largura, int altura, bool ativo, int fonte);
bool PainelObjetoAutoFitFIX319(string nome);
void PainelDesativarAutoFitFIX319();
void PainelPrepararCompletoAutoFitFIX319(int &x,int &y,int &largura,int &altura);
void PainelConfigurarAutoFitFIX319(int baseX,int baseY,int baseW,int baseH,int &x,int &y,int &largura,int &altura);
int PainelAutoXFIX319(string nome,int x);
int PainelAutoYFIX319(string nome,int y);
int PainelAutoWFIX319(string nome,int largura);
int PainelAutoHFIX319(string nome,int altura);
int PainelAutoFonteFIX319(string nome,int fonte);
string ChaveControleMagicFIX285(long magic);
string ChaveControleOperacaoFIX284();
long MagicControleLocalFIX285();
string NomeLadoControleMagicFIX285(long magic);
ENUM_CONTROLE_OPERACAO_FIX284 EstadoControleMagicFIX285(long magic);
bool ControleBloqueiaMagicFIX285(long magic);
string TextoControleMagicFIX285(long magic);
bool ExistePosicaoAbertaControleLocalFIX285();
bool FecharPosicoesControleLocalFIX285(string motivo);
void InicializarControleOperacaoFIX284();
void SincronizarControleOperacaoFIX284(bool forcar=false);
void DefinirControleOperacaoFIX284(ENUM_CONTROLE_OPERACAO_FIX284 novoEstado, string motivo);
string TextoControleOperacaoFIX284();
bool ProcessarEncerramentoManualFIX284(bool forcar);
bool PainelCliqueControleOperacaoFIX284(string objeto);
void DesenharBotoesControleOperacaoFIX284(string pfx, int x, int y, int fonte);
void PnlBotaoControleFIX284(string nome, string texto, int x, int y, int largura, int altura, color fundo, color textoCor, color borda, int fonte);
void ObterHistoricoSelecionado(HistoricoPeriodo &h);
void ObterHistoricoPainelPrincipal(HistoricoPeriodo &h);
void CalcularHistoricoOperacaoAtual(HistoricoPeriodo &h);
void ObterHistoricoMagicLocalPainel(EstadoLado &e, HistoricoPeriodo &h);
void CalcularHistoricoPeriodoHeadGrupo(datetime inicio, datetime fim, HistoricoPeriodo &h, string nome, bool incluirAberto);
void MarcarInicioCicloOperacional(EstadoLado &estado);
string NomePeriodoHistoricoPainel(ENUM_PERIODO_HISTORICO_PAINEL periodo);
void CalcularHistoricoPeriodo(datetime inicio, datetime fim, HistoricoPeriodo &h, string nome, bool incluirAberto);
void InicializarMarcoHistoricoZero();
bool AplicarMarcoHistoricoZero(datetime &inicio, datetime fim, HistoricoPeriodo &h, string nome);
ulong CapturarMaiorTicketHistoricoExistente();
bool DealEhDepoisDoMarcoHistoricoZero(ulong deal);
void ZerarHistoricoPeriodo(HistoricoPeriodo &h, string nome);
ENUM_PERIODO_HISTORICO_PAINEL PeriodoIdPorNome(string nome);
void DefinirJanelaHistorico(HistoricoPeriodo &h, datetime inicio, datetime fim, bool incluirAberto);
bool HistoricoPeriodoCompativel(HistoricoPeriodo &h, ENUM_PERIODO_HISTORICO_PAINEL esperado);
void VerificarViradaDiaHistorico(datetime agora);
// FIX310: virada civil, painel diario e seletor FAVOR/CONTRA.
string ChaveControleDiaFIX310(string sufixo);
double AbertoAtualLadoFIX310(ENUM_LADO_ROBO lado);
void SalvarControleDiaFIX310(bool forcar);
void InicializarControleDiaFIX310();
void ProcessarViradaFinanceiraFIX310(datetime agora, bool forcar=false);
void AuditoriaViradaDiaFIX310(datetime agora);
double RealizadoHojeLadoFIX310(ENUM_LADO_ROBO lado);
double VariacaoAbertaHojeLadoFIX310(ENUM_LADO_ROBO lado);
double SaldoHojeLadoFIX310(ENUM_LADO_ROBO lado);
bool ExisteSinalContraValidoFIX310(ENUM_LADO_ROBO lado, string &detalhe);
bool ModoEntradaA0PermiteFIX310(EstadoLado &estado, string &motivo);
string TextoModoEntradaA0FIX310();
bool PrimeiraOrdemLivreProtegidaFIX314();
bool PrimeiraOrdemDesligadaFIX314();
string TextoComoAbrirPrimeiraOrdemFIX314();
// FIX311: fonte unica e auditoria de historico/Magics.
string FamiliaContratoHistoricoFIX347(string simbolo);
bool SimboloAceitoHistoricoFIX347(string simbolo);
datetime InicioOntemCivilFIX311(datetime referencia);
bool PosicaoTemIdentidadeAR100FIX311(long magic);
bool MagicHistoricoCompraFIX458(long magic);
bool MagicHistoricoVendaFIX458(long magic);
bool MagicPertenceHistoricoFinanceiroFIX458(long magic);
long TipoLadoHistoricoMagicFIX458(long magic);
long TipoPosicaoEsperadoMagicPainelFIX316(long magic);
bool PosicaoSelecionadaPertencePainelFIX316(long magic);
bool PosicaoSelecionadaPertenceEstadoFIX317(EstadoLado &estado);
bool DealPertenceHistoricoPainelFIX316(ulong deal);
void ObterEntradasAbertasPainelFIX316(double &qtdCompra, double &qtdVenda, int &entradasCompra, int &entradasVenda);
void AplicarFallbackEntradasAbertasHistoricoFIX316(HistoricoPeriodo &h);
void CalcularHistoricoPeriodoCoreFIX311(datetime inicio, datetime fim, HistoricoPeriodo &h, string nome, bool incluirAberto, long magicFiltro);
double AbertoPeriodoLadoFIX311(HistoricoPeriodo &h, ENUM_LADO_ROBO lado);
double SaldoPeriodoLadoFIX311(HistoricoPeriodo &h, ENUM_LADO_ROBO lado);
void AuditoriaHistoricoMagicFIX311(bool forcar);
void InicializarHistoricoPainelZerado();
void CapturarMarcoHistoricoInicial();
bool DealEhDepoisDoMarcoHistoricoSessao(ulong deal);
datetime AgoraServidorHistorico();
datetime InicioDoDia(datetime ref);
datetime InicioDiasAtras(int quantidadeDias);
double ResultadoDealHistorico(ulong deal);
bool CalcularLucroEsperadoDealReaisFIX313(ulong dealSaida, double &lucroEsperado, double &precoMedio, double &volumeSaida);
double ResultadoDealSeguroReaisFIX313(ulong deal);
bool ObterResultadoDealCacheFIX313(ulong deal, double &resultado);
void SalvarResultadoDealCacheFIX313(ulong deal, double resultado);
bool AuditarUnidadeFinanceiraHojeFIX313(int &corrigidos, int &semBase, double &somaBruta, double &somaSegura);
int ContarSaidasRecentesFIX313(int janelaSegundos);
bool ProtecaoRepeticaoPermiteNovaOrdemFIX313(EstadoLado &estado, string contexto);
bool DealEhParcialHistoricaReal(ulong deal);
bool DealEhDoRoboHistorico(ulong deal);
bool DealEhDoRobo(ulong deal);
bool DealEhSaidaParcial(long entry);
double ParcialHistoricoDoLado(HistoricoPeriodo &h, ENUM_LADO_ROBO lado);
int TradesLucroHistoricoDoLado(HistoricoPeriodo &h, ENUM_LADO_ROBO lado);
int TradesPrejuHistoricoDoLado(HistoricoPeriodo &h, ENUM_LADO_ROBO lado);
string LinhaHistoricoPeriodo(HistoricoPeriodo &h);
double CalcularScoreFluxo();
void AtualizarCurvaVolumeHoraHora(int shiftFiltro);
datetime InicioDia(datetime t);
datetime MontarHorarioNoDia(datetime dia, string horaMinuto);
datetime DiaAnteriorComBarras(datetime diaAtual);
double SomarVolumePeriodo(datetime inicio, datetime fim, bool financeiro);
int SlotHoraHora(datetime t, datetime inicio, int slotMinutos, int maxSlots);
double LimiteVolumeQtdDinamico(RegraFiltros &f);
double LimiteVolumeFinDinamico(RegraFiltros &f);
ENUM_STATUS_MERCADO ClassificarMercado(double score);
string NomeStatusMercado(ENUM_STATUS_MERCADO status);
string TextoDXStatus();
color CorMagicPiscando(color corBase);
ENUM_LADO_ROBO LadoCardLocalPainelAtual();
void ObterEstadoMotorPainelLocal(EstadoLado &destino);
void ObterEstadoResumoPainelLocal(EstadoLado &destino);
string TituloResumoLocalPainel(EstadoLado &e);
bool CardFinanceiroEhFoco(EstadoLado &e);
void CalcularResumoFinanceiroSlotPainel(EstadoLado &e, HistoricoPeriodo &h, ResumoFinanceiroPainel &r);
void CalcularResumoFinanceiroTotalAB(ResumoFinanceiroPainel &a, ResumoFinanceiroPainel &b, ResumoFinanceiroPainel &t);
string TextoFormulaSaldoCard3(ResumoFinanceiroPainel &a, ResumoFinanceiroPainel &b, ResumoFinanceiroPainel &t);
void ZerarFotoCestaAB(FotoCestaAB &f);
datetime InicioHistoricoCestaABOficial();
void CalcularFotoCestaABOficial(FotoCestaAB &f, bool usarSnapshotAberto=false);
string TextoLogFotoCestaAB(FotoCestaAB &f);
void LogCestaABDetalhado(string contexto, bool forcar=false);
void LogDealSaidaCestaAB(ulong deal);
string NomeTipoPosicaoHedge(long type);
string NomeTipoDealHedge(long type);
string NomeEntryDealHedge(long entry);
int ContarPosicoesAbertasGrupoAB();
string TextoPosicoesAbertasGrupoAB();
string TextoHedgeStatusAB(FotoCestaAB &f);
void LogHedgeCompleto(string contexto, string etapa, string motivo, ulong ticket, ulong deal, long magic, uint retcode, int erro, double volume, double preco, bool forcar);
double LinhaStopFullAtualHedgeAB();
string MotivoLinhaStopFullHedgeAB();
void LogStopFullHedgeAB(string contexto, bool forcar=false);
bool ExistePosicaoAbertaGrupoTotalAB();
bool CestaABTemDuasPontasAbertasGrupo();
bool FecharCestaABOficial(string motivo);
void AtualizarEstadoFimDiaFIX215();
bool BloquearNovasOperacoesFimDiaFIX215();
bool HorarioFechamentoObrigatorioFIX215();
bool ProcessarFechamentoFimDiaFIX215();
bool GerenciarStopDiaMestreFIX320();
string TextoStatusFimDiaFIX215();
void DispararMsgBoxVisualFIX226(string titulo, string linha1, string linha2);
bool MsgBoxVisualAtivaFIX226();
void LimparMsgBoxVisualFIX226(string pfx);
void AvaliarEventoMsgBoxFIX226(string contexto, string mensagem, bool importante);
bool MagicPertencePainelTotalAB(long magic);
bool GrupoHeadTemPosicaoTipo(long tipo);
bool LadoObrigatorioOpostoGrupoHead(ENUM_LADO_ROBO lado);
bool LadoBloqueadoPorOpostoGrupoHead(ENUM_LADO_ROBO lado);
string ChaveParABCompletadoFIX274();
bool ParABJaCompletadoFIX274();
void AtualizarEstadoParABFIX274();
bool ExecutarAuditoriaTesteFIX274();
string TextoGrupoMagicsTotalAB();
void CalcularAbertoTotalABGrupoDiretoBase(double &qtdCompra, double &qtdVenda, double &totalBruto, double &abertoCompra, double &abertoVenda, double &abertoTotal);
void CalcularAbertoTotalABGrupoDireto(double &qtdCompra, double &qtdVenda, double &totalBruto, double &abertoCompra, double &abertoVenda, double &abertoTotal);
string TextoFocoUnico(EstadoLado &e);
string TextoMagicTopoPiscando();
double ContratosPlanejadosTotal();
void LimparPlotagemDX();
void AtualizarPlotagemDX();
void GarantirDXIndicadorNoGrafico();
bool FiltroVisualSelecionadoFIX343(string filtro);
bool GarantirOsciladoresSelecionadosFIX343();
void RemoverOsciladoresSelecionadosFIX343();
bool LocalizarIndicadorPorPrefixoFIX345(string prefixo,int &janela,string &nome);
bool GarantirDXVisualEditavelFIX345();
void RemoverDXVisualEditavelFIX345();
void DetectarFechamentoVisualUsuarioFIX345();
int PeriodoMediaGraficoEfetivo();
void GarantirMedia25NoGrafico();
void AtualizarBandasMedia25Grafico(bool forcar=false);
void LimparBandasMedia25Grafico();
void AplicarGraficoLimpoFIX353();
void AtualizarPainelFinanceiroImediatoFIX353(bool forcarHistorico=false);
bool CriarSegmentoMedia25(string nome, datetime t1, double p1, datetime t2, double p2, color cor, ENUM_LINE_STYLE estilo, int largura);
void LimparEntradasHistoricasGraficoFIX385();
void AtualizarEntradasHistoricasGraficoFIX385(bool forcar=false);
void PlotarEntradaHistoricaNoGraficoFIX385(ulong deal);
void PlotarPosicoesAbertasProvisoriasFIX390();
bool DealEhEntradaPlotavelGraficoFIX385(ulong deal);
void RemoverADXVisualLegado();
void ConfigurarObjetoAtrasPainel(string nome);
string TextoDXConfigPainel();
string NomeModoPainelVisual(ENUM_MODO_PAINEL_VISUAL modo);
string TextoCortarPainel(string texto, int larguraPx, int fonte);
string PnlMoedaBRL(double valor);
string TextoMoedaPainelCurto(double valor);
void PainelTextoCortado(string nome, string texto, int x, int y, color cor, int fonte, string fontName, int larguraPx);
void GerenciarLado(ENUM_LADO_ROBO lado);
void GerenciarEstadoLado(EstadoLado &estado);
bool TipoOperacaoPermiteLado(ENUM_LADO_ROBO lado);
string TextoTipoOperacaoParametro();
bool GerenciarProtecaoLado(EstadoLado &estado);
bool GerenciarParciaisLado(EstadoLado &estado);
double ResultadoProtecaoOperacaoLado(EstadoLado &estado);
double CalcularDefesaCurtaPorDegrau(double melhorLucro);
string NomeRegimeCorredorFIX338(ENUM_REGIME_CORREDOR_FIX338 regime);
ENUM_REGIME_CORREDOR_FIX338 AvaliarRegimeCorredorFIX338(long tipo, int &favoraveis, int &contrarios, string &leitura);
double CalcularPisoCorredorFIX338(double melhorLucro, double ativacao, double pisoInicial, double degrau, double folga);
bool CorredorAlvoPontaViraMarcoFIX338();
bool CorredorMetaABViraMarcoFIX338();
double CalcularDefesaMaiorCestaAB(double melhorLucro);
bool GerenciarProtecaoMaiorCestaAB();
bool CestaABTemDuasPontasAbertas();
bool GerenciarParcialProtecaoCurtaCestaAB();
bool GerenciarLucroPontaGanhadoraHedgeAB();
bool CestaABTemAlgumaPosicaoFIX195();
void ResetarEstadoPontaSimplesFIX195(EstadoPontaSimplesFIX195 &e);
void PrepararNovoCicloPontaFIX275(EstadoLado &estado);
void AtualizarCicloMestreSimplesFIX195();
void ResetarCicloMestreSimplesFIX195SeFlat();
bool ProcessarEstadoPontaSimplesFIX195(EstadoPontaSimplesFIX195 &p, EstadoLado &estado, long tipo, double lucroPonta, double volumePonta);
bool ProcessarPontaSimplesFIX195(long tipo,double lucroPonta,double volumePonta);
bool ProcessarGerenciamentoSimplesInstanciaFIX255();
bool AplicarMagicsCompactosFIX255(string &motivo);
bool JanelaAtualEhA_FIX255();
bool JanelaAtualEhB_FIX255();
ENUM_LADO_ROBO LadoOperacionalInstanciaFIX255();
long MagicOperacionalInstanciaFIX255();
bool InstanciaGerenciaLadoFIX255(ENUM_LADO_ROBO lado);
bool LadoHabilitadoUsuarioFIX346(ENUM_LADO_ROBO lado);
string TextoLadosHabilitadosFIX346();
bool InstanciaMestreGrupoFIX255();
string NomeJanelaInstanciaFIX255();
ENUM_TIMEFRAMES TimeframeFiltroAtualFIX255();
ENUM_TIMEFRAMES TimeframeEntradaAtualFIX255();
string PrefixoCoordenacaoMagicsFIX256();
string ChaveCoordenacaoMagicsFIX256(string campo);
datetime AgoraCoordenacaoMagicsFIX256();
bool RegistroJanelaAtivoFIX256(bool janelaA, long &chartId, datetime &heartbeat);
bool AdquirirLockCoordenacaoMagicsFIX256();
void LiberarLockCoordenacaoMagicsFIX256();
bool RegistrarCoordenacaoMagicsFIX256(string &motivo);
void AtualizarCoordenacaoMagicsFIX256(bool forcar=false);
void DesregistrarCoordenacaoMagicsFIX256();
bool CoordenacaoPermiteNovaOrdemFIX256(EstadoLado &estado, string contexto);
int NivelAumentoComentarioFIX207(string comentario);
int NivelAumentoDealRobustoFIX296(ulong deal);
void ReconstruirMarcacaoAumentosRealizadosFIX296(EstadoLado &estado, datetime inicio);
void SincronizarRealizacoesAumentosFIX296(bool forcar);

int NivelAumentoPosicaoFIX212(EstadoLado &estado, ulong ticket, string comentario);
bool ObterPosicaoAumentoNivelFIX212(EstadoLado &estado, int nivel, ulong &ticket, double &precoEntrada, double &volume, long &tipo);
double PrecoRealizacaoAumentoFIX212(long tipo, double precoEntrada, double volume, double alvoReais);
double PrecoLossAumentoFIX321(long tipo, double precoEntrada, double volume, double lossReais);
void SalvarAlvoLinhaAumentoFIX212(EstadoLado &estado, int nivel, double precoAlvo);
double AlvoLinhaAumentoFIX212(EstadoLado &estado, int nivel);
void MarcarAumentoRealizadoFIX212(EstadoLado &estado, int nivel, double precoRealizado);
bool AumentoRealizadoFIX212(EstadoLado &estado, int nivel, double &precoRealizado);
void ResetarRastreamentoAumentosFIX212(EstadoLado &estado);
string NomeBasePrecoAumentoFIX220();
string ChavePrecoEntradaAumentoFIX220(EstadoLado &estado, int nivel);
void SalvarPrecoEntradaAumentoFIX220(EstadoLado &estado, int nivel, double preco);
double PrecoEntradaAumentoFIX220(EstadoLado &estado, int nivel);
void RegistrarAuditoriaVisualAumentoFIX358(EstadoLado &estado,int nivel,double programado,double executado);
double PrecoProgramadoAuditoriaAumentoFIX358(EstadoLado &estado,int nivel);
double PrecoExecutadoAuditoriaAumentoFIX358(EstadoLado &estado,int nivel);
void RestaurarPrecosEntradaAumentosFIX220(EstadoLado &estado);
double PassoAumentoPontosFIX220(int indiceZero);
double UltimoPrecoAumentoAntesFIX220(EstadoLado &estado, int indiceZero, int &nivelEncontrado);
string ChaveAncoraRearmeA1FIX225(EstadoLado &estado);
string ChaveCicloRearmeA1FIX225(EstadoLado &estado);
double AncoraRearmeA1FIX225(EstadoLado &estado);
int CicloRearmeA1FIX225(EstadoLado &estado);
void SalvarAncoraRearmeA1FIX225(EstadoLado &estado, double preco);
string ChaveNivelInicioRearmeFIX248(EstadoLado &estado);
int NivelInicioRearmeFIX248(EstadoLado &estado);
void SalvarContextoRearmeFIX248(EstadoLado &estado, double precoMedio, int nivelInicio);
void LimparContextoRearmeFIX248(EstadoLado &estado);
string ChaveRearmePendenteFIX251(EstadoLado &estado, string campo);
void PersistirRearmePendenteFIX251(EstadoLado &estado);
void RestaurarRearmePendenteFIX251(EstadoLado &estado);
void LimparRearmePendenteFIX251(EstadoLado &estado);
bool RearmeParcialPendenteFIX248(EstadoLado &estado);
void AgendarRearmeDinamicoAposParcialFIX248(EstadoLado &estado, int nivelRealizado, double volumeRemovido);
bool ProcessarRearmeDinamicoPendenteFIX248(EstadoLado &estado);
bool RecuperarRearmeSemEventoFIX452(EstadoLado &estado);
int PrimeiroNivelRearmavelFIX248(EstadoLado &estado, int nivelRealizado);
void LimparMemoriaNiveisAPartirFIX248(EstadoLado &estado, int nivelInicial);
bool AplicarRearmeDinamicoAposParcialFIX248(EstadoLado &estado, int nivelRealizado, double volumeRemovido);
bool PrecoNoLadoGatilhoAumentoFIX248(EstadoLado &estado, double linha);
double PrecoExecutavelAumentoFIX363(EstadoLado &estado);
bool PrecoAumentoNaLinhaOuMelhorFIX363(EstadoLado &estado,double linha,string &status);
bool ValidarAumentoFinalAntesEnvioFIX363(EstadoLado &estado,int indiceZero,double linhaProgramada,string &status);
void PrepararNovoCruzamentoNivelFIX248(EstadoLado &estado, int nivel);
bool NovoCruzamentoLiberadoFIX248(EstadoLado &estado, int nivel, double linha, string &status);
bool EscadaA1RearmadaFIX225(EstadoLado &estado);
int ProximoIndiceAumentoSequencialFIX218(EstadoLado &estado);
double CalcularDefesaDegrauFIX281(double melhorLucro, double ativacao, double passo);
void ResetarTrailAumentoFIX281(EstadoTrailAumentoFIX281 &trail);
bool ProcessarTicketAumentoFIX281(EstadoPontaSimplesFIX195 &p, EstadoLado &estado, long tipo, ulong ticket, int nivel, double volume, double lucroTicket, EstadoTrailAumentoFIX281 &trail);
void CalcularAumentosAbertosLadoFIX281(EstadoLado &estado, double &volumeAberto, double &financeiroAberto, int &ticketsAbertos);
void ReconstruirRealizacoesAumentosCicloFIX281(long magic, long tipoPosicao, datetime inicio, double &financeiro, double &volume, int &quantidade);
bool FecharTicketAumentoFIX207(EstadoLado &estado, ulong ticket, double volumeDesejado, int nivel, double lucroTicket, string motivoFIX281);
bool GerenciarRealizacaoAumentosPorTicketFIX207(EstadoPontaSimplesFIX195 &p, EstadoLado &estado, long tipo);
double ResultadoCicloPontaFIX207(long tipo, double lucroAberto);
bool FecharParcialGrupoPorTipo(long tipo, double volumeDesejado, string motivo);
void LimparLocksLucroPontaHedgeAB();
int HashTextoCurtoAB(string texto);
string ChaveGlobalCurtaAB();
string ChaveCicloGrupoTipoAB(long tipo);
void LimparLocksParciaisHedgeABPorPrefixo();
void ArmarProtecaoFinanceiraLado(EstadoLado &estado, string contexto, bool importante);
double NormalizarVolumeParaFechamento(double volume);
double CalcularVolumeParcialSeguro(double volumeAtual, double percentualVolume);
bool FecharParcialPosicoesLado(EstadoLado &estado, double volumeDesejado, string motivo);
bool GerenciarGainGlobalCestaAB();
bool GerenciarStopMovelCestaAB();
void ResetarCicloCestaABQuandoFlat();
bool RiscoOperacaoModoCesta();
double StopBaseCestaAB();
double GainGlobalCestaAB();
double ResultadoRealizadoCestaABAtual();
double ResultadoAbertoCestaABAtual();

double SaldoLiquidoCestaABAtual();
double StopMovelAbertoPermitidoCestaAB();
double EspacoStopRestanteCestaAB();
string TextoGainStopCestaPainel();
double CalcularDefesaTrailingLado(EstadoLado &estado);
bool DeveAtivarModoLongo(EstadoLado &estado);
bool SaidaTecnicaLonga(EstadoLado &estado, string &motivo);
bool GerenciadorAutorizaAumento(EstadoLado &estado, RegraAumento &aum);
bool PodeExecutarAumento(EstadoLado &estado, RegraAumento &aum, int indiceZero);
bool ExistePosicaoMagicQualquerInstancia(long magic);
string PrefixoLockCicloMagic(long magic);
string ChaveLockA0(EstadoLado &estado);
bool ExisteOrdemPendenteA0FIX257(EstadoLado &estado);
string ChaveLockAumento(EstadoLado &estado, int idx);
string ChaveLockAumentoConfirmadoFIX208(EstadoLado &estado, int idx);
bool ExisteOrdemPendenteAumentoFIX208(EstadoLado &estado, int idx);
double VolumePlanejadoAteAumentoFIX208(int idx);
void MarcarLockAumentoConfirmadoFIX208(EstadoLado &estado, int idx);
bool RegistrarLockCiclo(string chave);
void LiberarLockCiclo(string chave);
bool RegistrarLockA0(EstadoLado &estado);
bool RegistrarLockAumento(EstadoLado &estado, int idx);
bool LockAumentoJaRegistrado(EstadoLado &estado, int idx);
int AumentosExecutadosPlanejadosPorContratos(double contratos);
void LimparLocksCicloMagic(long magic);
bool ValidarTravasDeValidacaoInicial();
bool ExistePosicaoAR100Aberta();
bool PermitirEntradaA0PeloModoValidacao(EstadoLado &estado);
bool PermitirAumentoPeloModoValidacao(EstadoLado &estado, int idxAlvo);
string TextoModoValidacaoExecucao();
string NomeTimeframeCurto(ENUM_TIMEFRAMES tf);
bool PermiteEnvioOrdem(EstadoLado &estado, string contexto);
bool PermiteEnvioAumentoDiretoFIX211(EstadoLado &estado, string contexto);
bool ReentradaTimerAtivo();
bool STFTPermiteNovaEntrada(EstadoLado &estado);
void RegistrarSTFTFechamento(EstadoLado &estado, double resultado);
bool ExistePontaContrariaAberta(ENUM_LADO_ROBO lado);
bool BloquearA0OutraPontaAutomatica(EstadoLado &estado);
bool ExisteMesmoSentidoOutroMagicMesmoTF(EstadoLado &estado);
double ResultadoPontaContraria(ENUM_LADO_ROBO lado);
bool PontaContrariaNegativaParaHedge(ENUM_LADO_ROBO lado);
bool PermitirEntradaHedgeRecuperacao(EstadoLado &estado, string &motivo);
int  EscolherIndiceAumentoInteligente(EstadoLado &estado);
int  PrimeiroIndiceAumentoAtivoApartir(int inicio);
bool TimerAumentoLiberado(EstadoLado &estado, RegraAumento &aum, int indiceZero=-1);
bool PrecoChegouNivelAumentoNivel(EstadoLado &estado, RegraAumento &aum, int indiceZero);
void LimparConfirmacaoCandleAumentoFIX224(EstadoLado &estado, int indiceZero);
bool CandleAumentoConfirmadoFIX224(EstadoLado &estado, int indiceZero);
datetime CandleToqueAumentoFIX224(EstadoLado &estado, int indiceZero);
bool ConfirmarFechamentoCandleAumentoFIX224(EstadoLado &estado, int indiceZero, double linha, string &status);
string StatusCandleAumentoFIX224(EstadoLado &estado, int indiceZero);
bool ExecutarEntradaA0(EstadoLado &estado, RegraJanela &janela);
double VolumeAtualMagicServidor(EstadoLado &estado);
bool ExecutarAumento(EstadoLado &estado, RegraAumento &aum, int idx);
bool EnviarOrdemMercado(EstadoLado &estado, double volume, string comentario, string contextoEnvio);
void AplicarAmbienteExecucaoFIX342();
bool ExecutarAuditoriaProducaoFIX342(string &detalhes);
bool ValidarPreflightEntradaFIX342(EstadoLado &estado,MqlTradeRequest &req,string &motivo,MqlTradeCheckResult &check);
void ProcessarRetcodeEntradaFIX342(EstadoLado &estado,uint retcode,uint retcodeExterno,string contexto);
double CalcularStopServidorEntradaFIX342(ENUM_LADO_ROBO lado,double precoEntrada);
void GarantirStopsServidorFIX342(bool forcar=false);
bool ConfiguracaoParABCompativelFIX342(string &motivo);
double PrecoReferenciaFIX344(ENUM_REFERENCIA_PRECO_FIX344 referencia,string &origem);
bool ValidarRangeGridEntradaFIX344(EstadoLado &estado,double preco,string &motivo);
void AtualizarRangeGridGraficoFIX344(bool forcar=false);
void LimparRangeGridGraficoFIX344();
bool PermissoesTradingFIX279(ENUM_LADO_ROBO lado, string &motivo);
bool EnviarA0DiretoFIX279(EstadoLado &estado);
bool ProcessarEntradaDiretaFIX279();
bool FecharPosicoesLado(EstadoLado &estado, string motivo);
ENUM_ORDER_TYPE_FILLING TipoPreenchimentoSeguro();
double NormalizarVolume(double volume);
void RegistrarGerenciadorOrdens(EstadoLado &estado, string contexto, string mensagem, uint retcode, int erro, double volume, double preco, bool importante);
void FecharLogValidacaoCSV();
bool ContextoLogValidacaoRelevante(string contexto, string mensagem, bool importante);
string SanitizarCampoCSV(string texto);
void RegistrarLogValidacaoCSV(EstadoLado &estado, string contexto, string mensagem, uint retcode, int erro, double volume, double preco, bool importante);
void RegistrarLogValidacaoSistema(string contexto, string mensagem);
// FIX302 auditoria
void AplicarCenarioAuditoriaFIX302();
bool EntradaDiretaDemoEfetivaFIX302();
bool ModoContinuidadeTesteFIX352();
string FiltroEfetivoAuditoriaFIX302(string configurado);
void AuditoriaInicializarFIX302();
void AuditoriaResetarNiveisFIX302();
void AuditoriaAtualizarCicloFIX302();
void AuditoriaRegistrarEventoFIX302(EstadoLado &estado,string contexto,string mensagem,uint retcode,int erro,double volume,double preco,bool importante);
void AuditoriaRegistrarDealEntradaFIX302(ulong deal,int nivel);
void AuditoriaRegistrarDealSaidaFIX302(ulong deal,int nivel,double resultado);
void AuditoriaRegistrarDealBrutoFIX305(ulong deal,int nivel);
string AuditoriaCabecalhoDealsFIX305();
double ResultadoDealServidorFIX305(ulong deal);
double ComissaoManualDealFIX305(ulong deal);
double ComissaoAplicadaDealFIX305(ulong deal);
double ResultadoDealLiquidoAuditadoFIX305(ulong deal);
string NomeModoComissaoFIX305();
void AuditoriaFlushFIX302(bool forcar);
void AuditoriaFecharFIX302();
void AuditoriaRegistrarTempoTickFIX302(ulong micros);
void AuditoriaRegistrarTempoTimerFIX302(ulong micros);
void AuditoriaRegistrarTempoTradeFIX302(ulong micros);
void AuditoriaValidarGraficoFIX302(bool forcar);
void AuditoriaAtualizarTelaFIX302(bool forcar);
bool PainelCliqueAuditoriaFIX302(string objeto);
// FIX306 exportacao semanal externa
bool ExportacaoIniciarFIX306();
void ExportacaoProcessarTimerFIX306();
void ExportacaoFecharFIX306();
string ExportacaoStatusCurtoFIX306();
void ProcessarOnTickMotorFIX302();
void ProcessarOnTimerMotorFIX302();
void ProcessarOnTradeTransactionMotorFIX302(const MqlTradeTransaction& trans,const MqlTradeRequest& request,const MqlTradeResult& result);
void LimparSnapshotEntradaFiltros();
string TextoLadoOrdem(ENUM_LADO_ROBO lado);
string ValorBoolSN(bool v);
bool MontarDiagnosticoFiltros(RegraFiltros &f, ENUM_LADO_ROBO lado, string &resumo, string &detalhe, int &total, int &ok, string &m25Status, string &scoreStatus, double &scoreLado, string &hiloOK, string &strOK, string &dxOK, string &rsiOK, string &volqOK, string &volfOK, string &agrOK);
void RegistrarLogEntradaFiltros(EstadoLado &estado, string contexto, string tipoEntrada, RegraFiltros &f, bool decisaoLiberada, string motivo, bool importante);
void RegistrarDecisaoOperacional(EstadoLado &estado, string contexto, string mensagem);
void LogExpertsGerenciador(string assinatura, string contexto, EstadoLado &estado, string mensagem, bool importante);
string ResumoGerenciadorOrdens();
bool ExisteJanelaAtivaParaLado(ENUM_LADO_ROBO lado, RegraJanela &janelaOut);
bool AuditarLadosOpostosV36(string &motivo);
bool EstaDentroJanela(RegraJanela &j);
int MinutoAtualDoDia();
bool ValidarFiltros(RegraFiltros &f, ENUM_LADO_ROBO lado);
bool ValidarComparacao(double valor, string op, double limite);
double Media25FiltroValor(int shift);
ENUM_LADO_ROBO DirecaoMedia25Operacional();
bool Media25PermiteLado(ENUM_LADO_ROBO lado, string &motivo);
double ScoreDirecionalDoLado(ENUM_LADO_ROBO lado);
string TextoDirecaoMedia25();
void AtualizarPainelMestre();
void AtualizarPainelGrafico();
void AtualizarRodapePainelRapido();
void PainelChartRedrawLeve(bool clique=false);
void ReencaixarPainelInicialSeNecessario();
void LimparPainelGrafico();
void LimparTodosObjetosCOPA();
void LimparSomentePainelVisual();
void DesenharCardAumentos(EstadoLado &estado, int x, int y, int largura, int altura);
void DesenharCardHistorico(int x, int y, int largura, int altura);
bool ExistePosicaoMagicTipo(long magic, long tipo);
string TextoSelecaoHead();
string TextoHeadExterno();
bool SinalSaidaOperacaoLonga(EstadoLado &estado);
bool EscalonamentoGanhosAtivo();
double DefesaMetaDiaEscalonadaFIX331(double melhorLucro, double &etapaAtingida);
bool ValidarParametrosOperacionaisFIX331(string &erro);
double NivelEscalonamentoAtual(double melhorLucro);
double CalcularDefesaEscalonadaPorGanho(double melhorLucro);
string TextoEscalonamentoGanhosPainel(double melhorLucro);
void AtualizarProtecaoResultadoDia();
void PersistirProtecaoDiaEscalonadaFIX333();
bool g_ladosOpostosOKV36=true;
string g_ladosOpostosStatusV36="NAO AUDITADO";
string TextoPosicaoCard(EstadoLado &estado);
string TextoLadoCurto(ENUM_LADO_ROBO lado);
double ExposicaoMaximaLado(EstadoLado &estado);
double ExposicaoNegativaLado(EstadoLado &estado);
double ExposicaoNegativaTotalPainel();
double ResultadoAbertoTotalPainel();
double DistanciaPrecoPorFinanceiro(double valorReais, double volume);
double GatilhoParcialEfetivoPorVolume(double valorBaseReais, double volume);
double GatilhoParcialEfetivoLado(EstadoLado &estado, double valorBaseReais);
double GatilhoParcialEfetivoCestaAB(double valorBaseReais);
void AplicarParcialOperacaoCompacta();
void AplicarAumentosDiretoDasLinhasParametros();
bool ParcialOperacaoAtivaEfetiva();
double ParcialGatilhoBaseReaisEfetivo();
double ParcialPassoBaseReaisEfetivo();
double ParcialPercentualVolumeEfetivo();
bool ParcialPorContratoEfetivo();
bool ParcialRecuoAumentoAtivoEfetivo();
long TipoPosicaoPeloLadoEstado(EstadoLado &estado);
void ReaplicarParametrosAntesDoGrafico(string origem);
bool CalcularInfoGrupoTipoAB(long tipo, double &volume, double &precoMedio, double &lucroAberto, double &precoFechamento);
double LucroEstimadoGrupoTipoPorPreco(long tipo, double volume, double precoMedio, double precoFechamento);
double PrecoNivelParcialGraficoLado(EstadoLado &estado, double valorBaseNivel, double &valorNivelEfetivo, double &volumeReferencia);
double DistanciaAumentoPontosIndice(int indiceZero);
bool PrecoEntradaReferenciaGrupoTipoAB(long tipo, double &precoEntradaRef, double &volume, double &precoFechamento);
int AumentosExecutadosEfetivosLado(EstadoLado &estado, long tipo);
double PrecoNivelParcialRecuoAumento(EstadoLado &estado, long tipo, double recuoPontos, double &distAumentoPontos, double &distLinhaPontos, double &precoEntradaRef);
bool GerenciarParcialPorLinhaGraficoHeadAB();
double PrecoNivelAumentoValorIndice(EstadoLado &estado, int indiceZero);
string PrecoNivelAumentoTextoIndice(EstadoLado &estado, int indiceZero);
void LimparPlotagemOperacional();
void LimparPlotagemPrefixo(string prefixo);
void AtualizarPlotagemOperacional();
void PlotarLinhasOperacionaisLado(string prefixo, EstadoLado &estado);
void PlotarLinhaPrecoBox(string nomeBase, double preco, color corLinha, ENUM_LINE_STYLE estilo, int larguraLinha, string legenda, color corTexto, color corFundo, int yAjuste);
double ExposicaoMaximaTotal();
string FormatarMoeda(double valor);
color CorFinanceiro(double valor);
color CorStatusTexto(string status);
color CorLadoTexto(ENUM_LADO_ROBO lado);


#endif // COPA_PROTOTIPOS_MOTOR_MQH
